### ISSUE TITLE
add default county and state to Locate query

### ISSUE THREAD

**Issue by joemerante** [codeforamerica/prepared.ly#11]
When searching without city and state, such as '1234 Garden St', the app breaks.  Searching '1234 Garden St TX' brings up that address in Nuevo Laredo, TX which is in the Southeast corner of the state.  Searching '1234 Garden St Travis County TX' brings up the Garden St in Austin.

**Comment by tinio** [comment]
This breaks because it tries to look up the risk level for a location which we don't have data (ie outside texas). So instead of adding a default county and state, instead we'll output the proper message that a result was not found:
https://skitch.com/tinio/825ih/preparedly
