### ISSUE TITLE
Fix links on Resources page

### ISSUE THREAD

**Issue by ssfinney** [codeforamerica/prepared.ly#44]
On [the Resources page](https://github.com/codeforamerica/prepared.ly/blob/master/app/views/resources/index.html.erb), there are two links that point to "http://prepared.ly/#contact-section". This link leads to the homepage, but not to any contact section.

One is under "Become a Firewise Community".
The other is under "Contact AFD".

**Comment by joemerante** [comment]
As the text suggests, those links lead to a form where users can contact a wildfire specialist with a question. If you are not logged into the site and click the link, it will just take you to the home page since #contact-section is only visible to authenticated users.

**Comment by ssfinney** [comment]
I see. I should have been more mindful. Sorry for the spam!
