### ISSUE TITLE
validate password field when user registers or updates account

### ISSUE THREAD

**Issue by joemerante** [codeforamerica/prepared.ly#8]
If a new user's password is too short on the sign up page, the app breaks when it tries to add the user.  Perhaps adding helper text, helper AJAX, or just an alert that the password is too short/uncomplicated.  Need to review devise code/docs.

**Comment by tinio** [comment]
the error here looks to be more of an issue of trying to modify the user instance which hasn't been created yet. will add a check so it doesn't break

**Comment by joemerante** [comment]
are you sure it's not both?  I just tried to create user 'josh@yahoo.com'
with a valid phone number and password of 'code' and received the following
error:

NoMethodError in Users::RegistrationsController#create

undefined method `referral_code=' for nil:NilClass
app/controllers/users/registrations_controller.rb:4:in`create'

Request
Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"JJH3WJRKESXEHK/V9iio6xiXiUTQWN6YuyNSBfHKDHU=",
 "user"=>{"email"=>"josh@yahoo.com",
 "phone"=>"9146727180",
 "password"=>"[FILTERED]",
 "password_confirmation"=>"[FILTERED]"},
 "commit"=>"Sign up"}

On Tue, May 8, 2012 at 4:10 PM, Aurelio Tinio <
reply@reply.github.com

**Comment by joemerante** [comment]
nevermind, didn't read your comment closely enough the first time.
